version: '3.7'

networks:
    default:
         name: NETWORKNAME
         external: true

services:
    shoppinglistbackend:
        container_name: ShoppingListBackend
        stdin_open: true
        tty: true
        image: shoppinglistbackend:latest
        hostname: ShoppingListBackend
        environment:
               - AUTH_KEY=YOUR_AUTH_KEY
               - ShoppingList_User=ShoppingList
               - ShoppingList_Password=DB_PASSWORD
               - ShoppingList_Host=DB_HOST
               - ShoppingList_DB=DB_DATABASE
        # Allow http://localhost on CORS HEADER
        networks: 
            - default
        restart: always
